INSERT INTO TBL_SONGS (SONG_ID, AUTHOR_NAME, SONG_NAME, SONG_POPULARITY) VALUES (1, 'ABC', 'abc');
INSERT INTO TBL_SONGS (SONG_ID, AUTHOR_NAME, SONG_NAME, SONG_POPULARITY) VALUES (2, 'ABD', 'aasd');
INSERT INTO TBL_SONGS (SONG_ID, AUTHOR_NAME, SONG_NAME, SONG_POPULARITY) VALUES (3, 'ABE', 'fggfh');
INSERT INTO TBL_SONGS (SONG_ID, AUTHOR_NAME, SONG_NAME, SONG_POPULARITY) VALUES (4, 'ABF', '3245s');
INSERT INTO TBL_SONGS (SONG_ID, AUTHOR_NAME, SONG_NAME, SONG_POPULARITY) VALUES (5, 'ABG', 'cvc5');
INSERT INTO TBL_SONGS (SONG_ID, AUTHOR_NAME, SONG_NAME, SONG_POPULARITY) VALUES (6, 'ABH', '999kk');
INSERT INTO TBL_SONGS (SONG_ID, AUTHOR_NAME, SONG_NAME, SONG_POPULARITY) VALUES (7, 'Mindaugas', 'abc');